// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalkOfFameServer.Database;

#nullable disable

namespace WalkOfFameServer.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WalkOfFameServer.Models.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.ArticleContent", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArticleId");

                    b.ToTable("ArticleContents");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Characters.Character", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("BirthCityId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("Money")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BirthCityId");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Characters.CharacterRelationship", b =>
                {
                    b.Property<long>("CharacterOneId")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterTwoId")
                        .HasColumnType("bigint");

                    b.Property<int>("CharacterOneFriendship")
                        .HasColumnType("int");

                    b.Property<int>("CharacterOneHate")
                        .HasColumnType("int");

                    b.Property<int>("CharacterOneLove")
                        .HasColumnType("int");

                    b.Property<int>("CharacterTwoFriendship")
                        .HasColumnType("int");

                    b.Property<int>("CharacterTwoHate")
                        .HasColumnType("int");

                    b.Property<int>("CharacterTwoLove")
                        .HasColumnType("int");

                    b.HasKey("CharacterOneId", "CharacterTwoId");

                    b.HasIndex("CharacterTwoId");

                    b.ToTable("CharacterRelationships");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DefaultLocationId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1111516587862528012L,
                            CountryId = 1111516587862528000L,
                            Name = "city.brazil.sao_paulo",
                            Timezone = "America/Sao_Paulo"
                        },
                        new
                        {
                            Id = 1111516587862528013L,
                            CountryId = 1111516587862528004L,
                            Name = "city.turkey.istanbul",
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 1111516587862528014L,
                            CountryId = 1111516587862528006L,
                            Name = "city.mexico.mexico_city",
                            Timezone = "America/Mexico_City"
                        },
                        new
                        {
                            Id = 1111516587862528015L,
                            CountryId = 1111516587862528009L,
                            Name = "city.germany.berlin",
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            Id = 1111516587862528016L,
                            CountryId = 1111516587862528011L,
                            Name = "city.italy.rome",
                            Timezone = "Europe/Rome"
                        },
                        new
                        {
                            Id = 1111516587862528017L,
                            CountryId = 1111516587862528010L,
                            Name = "city.united_kingdom.london",
                            Timezone = "Europe/London"
                        },
                        new
                        {
                            Id = 1111516587862528018L,
                            CountryId = 1111516587862528008L,
                            Name = "city.canada.quebec",
                            Timezone = "America/Toronto"
                        },
                        new
                        {
                            Id = 1111516587862528019L,
                            CountryId = 1111516587862528007L,
                            Name = "city.united_states.los_angeles",
                            Timezone = "America/Los_Angeles"
                        },
                        new
                        {
                            Id = 1111516587862528020L,
                            CountryId = 1111516587862528005L,
                            Name = "city.china.beijing",
                            Timezone = "Asia/Shanghai"
                        },
                        new
                        {
                            Id = 1111516587862528021L,
                            CountryId = 1111516587862528003L,
                            Name = "city.south_korea.seoul",
                            Timezone = "Asia/Seoul"
                        },
                        new
                        {
                            Id = 1111516587862528022L,
                            CountryId = 1111516587862528002L,
                            Name = "city.france.cannes",
                            Timezone = "Europe/Paris"
                        },
                        new
                        {
                            Id = 1111516587862528023L,
                            CountryId = 1111516587862528002L,
                            Name = "city.france.paris",
                            Timezone = "Europe/Paris"
                        },
                        new
                        {
                            Id = 1111516587862528024L,
                            CountryId = 1111516587862528001L,
                            Name = "city.india.mumbai",
                            Timezone = "Asia/Kolkata"
                        });
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1111516587862528000L,
                            Name = "country.brazil"
                        },
                        new
                        {
                            Id = 1111516587862528001L,
                            Name = "country.india"
                        },
                        new
                        {
                            Id = 1111516587862528002L,
                            Name = "country.france"
                        },
                        new
                        {
                            Id = 1111516587862528003L,
                            Name = "country.south_korea"
                        },
                        new
                        {
                            Id = 1111516587862528004L,
                            Name = "country.turkey"
                        },
                        new
                        {
                            Id = 1111516587862528005L,
                            Name = "country.china"
                        },
                        new
                        {
                            Id = 1111516587862528006L,
                            Name = "country.mexico"
                        },
                        new
                        {
                            Id = 1111516587862528007L,
                            Name = "country.united_states"
                        },
                        new
                        {
                            Id = 1111516587862528008L,
                            Name = "country.canada"
                        },
                        new
                        {
                            Id = 1111516587862528009L,
                            Name = "country.germany"
                        },
                        new
                        {
                            Id = 1111516587862528010L,
                            Name = "country.united_kingdom"
                        },
                        new
                        {
                            Id = 1111516587862528011L,
                            Name = "country.italy"
                        });
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<ulong>("Money")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Scoring")
                        .HasColumnType("int");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1111516587862528102L,
                            LocationType = 7,
                            Money = 0ul,
                            Name = "Prefeitura de São Paulo",
                            Quality = 0,
                            Scoring = 14,
                            ZoneId = 1111516587862528025L
                        });
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.Zone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<int>("InfrastructureQuality")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 1111516587862528025L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.praca_da_se",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528026L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.sultanahmet",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528027L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.cuauhtemoc",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528028L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.mitte",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528029L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.municipio_i",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528030L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.city_of_london",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528031L,
                            CityId = 1111516587862528018L,
                            InfrastructureQuality = 0,
                            Name = "zone.canada.quebec.vieux_quebec",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528032L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.downtown_la",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528033L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.dongcheng",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528034L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "zone.south_korea.seoul.jongno",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528035L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.cannes_centre",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528036L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.paris_1er",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528037L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.south_mumbai",
                            Quality = 0,
                            Type = 1
                        },
                        new
                        {
                            Id = 1111516587862528038L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.higienopolis",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528039L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.bebek",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528040L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.polanco",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528041L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.charlottenburg",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528042L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.trastevere",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528043L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.kensington",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528044L,
                            CityId = 1111516587862528018L,
                            InfrastructureQuality = 0,
                            Name = "zone.canada.quebec.cap_rouge",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528045L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.beverly_hills",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528046L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.chaoyang",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528047L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "one.south_korea.seoul.gangnam",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528048L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.la_bocca",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528049L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.montmartre",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528050L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.bandra",
                            Quality = 0,
                            Type = 2
                        },
                        new
                        {
                            Id = 1111516587862528051L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.paulista",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528052L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.nisantasi",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528053L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.zona_rosa",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528054L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.potsdamer_platz",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528055L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.via_del_corso",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528056L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.soho",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528057L,
                            CityId = 1111516587862528018L,
                            InfrastructureQuality = 0,
                            Name = "zone.canada.quebec.saint_roch",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528058L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.hollywood",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528059L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.sanlitun",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528060L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "zone.south_korea.seoul.myeongdong",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528061L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.la_croisette",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528062L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.champs_elysees",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528063L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.colaba",
                            Quality = 0,
                            Type = 3
                        },
                        new
                        {
                            Id = 1111516587862528064L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.cidade_industrial",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528065L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.tuzla",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528066L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.industrial_vallejo",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528067L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.industriepark_berlin",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528068L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.ostiense",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528069L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.park_royal",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528070L,
                            CityId = 1111516587862528018L,
                            InfrastructureQuality = 0,
                            Name = "zone.canada.quebec.par_industriel_quebec",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528071L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.industrial_district",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528072L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.beijing_economic_technological_dev_area",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528073L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "zone.south_korea.seoul.digital_media_city",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528074L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.cannes_la_bocca",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528075L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.paris_saclay",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528076L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.mahape",
                            Quality = 0,
                            Type = 4
                        },
                        new
                        {
                            Id = 1111516587862528077L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.embu_das_artes",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528078L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.polonezkoy",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528079L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.xochimilco",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528080L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.spreewald",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528081L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.castelli_romani",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528082L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.kent_countryside",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528083L,
                            CityId = 1111516587862528018L,
                            InfrastructureQuality = 0,
                            Name = "zone.canada.quebec.charlevoix",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528084L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.malibu_wine_safari",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528085L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.mutianyu_great_wall",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528086L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "zone.south_korea.seoul.bukhansan_national_park",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528087L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.ile_saint_marguerite",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528088L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.versailles",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528089L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.elephanta_caves",
                            Quality = 0,
                            Type = 5
                        },
                        new
                        {
                            Id = 1111516587862528090L,
                            CityId = 1111516587862528012L,
                            InfrastructureQuality = 0,
                            Name = "zone.brazil.sao_paulo.heliopolis",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528091L,
                            CityId = 1111516587862528013L,
                            InfrastructureQuality = 0,
                            Name = "zone.turkey.istanbul.tarlabasi",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528092L,
                            CityId = 1111516587862528014L,
                            InfrastructureQuality = 0,
                            Name = "zone.mexico.mexico_city.neza",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528093L,
                            CityId = 1111516587862528015L,
                            InfrastructureQuality = 0,
                            Name = "zone.germany.berlin.rudow",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528094L,
                            CityId = 1111516587862528016L,
                            InfrastructureQuality = 0,
                            Name = "zone.italy.rome.tor_bella_monaca",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528095L,
                            CityId = 1111516587862528017L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_kingdom.london.brixton",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528096L,
                            CityId = 1111516587862528019L,
                            InfrastructureQuality = 0,
                            Name = "zone.united_states.los_angeles.skid_row",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528097L,
                            CityId = 1111516587862528020L,
                            InfrastructureQuality = 0,
                            Name = "zone.china.beijing.migrant_villages",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528098L,
                            CityId = 1111516587862528021L,
                            InfrastructureQuality = 0,
                            Name = "zone.south_korea.seoul.guryong_village",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528099L,
                            CityId = 1111516587862528022L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.cannes.les_moulieres",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528100L,
                            CityId = 1111516587862528023L,
                            InfrastructureQuality = 0,
                            Name = "zone.france.paris.banlieues",
                            Quality = 0,
                            Type = 6
                        },
                        new
                        {
                            Id = 1111516587862528101L,
                            CityId = 1111516587862528024L,
                            InfrastructureQuality = 0,
                            Name = "zone.india.mumbai.dharavi",
                            Quality = 0,
                            Type = 6
                        });
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Companies.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<ulong>("Money")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.ArticleContent", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Article", "Article")
                        .WithMany("Contents")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Characters.Character", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Cities.City", "BirthCity")
                        .WithMany()
                        .HasForeignKey("BirthCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalkOfFameServer.Models.Cities.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalkOfFameServer.Models.Users.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthCity");

                    b.Navigation("CurrentLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Characters.CharacterRelationship", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Characters.Character", "CharacterOne")
                        .WithMany("RelationshipsAsCharacterOne")
                        .HasForeignKey("CharacterOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalkOfFameServer.Models.Characters.Character", "CharacterTwo")
                        .WithMany("RelationshipsAsCharacterTwo")
                        .HasForeignKey("CharacterTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterOne");

                    b.Navigation("CharacterTwo");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.City", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Cities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalkOfFameServer.Models.Cities.Location", "DefaultLocation")
                        .WithMany()
                        .HasForeignKey("DefaultLocationId");

                    b.Navigation("Country");

                    b.Navigation("DefaultLocation");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.Location", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("WalkOfFameServer.Models.Characters.Character", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("WalkOfFameServer.Models.Cities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Owner");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Cities.Zone", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Cities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Companies.Company", b =>
                {
                    b.HasOne("WalkOfFameServer.Models.Cities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Article", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Characters.Character", b =>
                {
                    b.Navigation("RelationshipsAsCharacterOne");

                    b.Navigation("RelationshipsAsCharacterTwo");
                });

            modelBuilder.Entity("WalkOfFameServer.Models.Users.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
